### ISSUE TITLE
Plugin binaries

### ISSUE THREAD

**Issue by leavittx** [artistsandengineers/AE_HapTools#1]
Hi there! I was unsuccessful with building AE_HapTools from sources (dx11 project reference seems to be missing, etc). 

Could you provide a plugin binary along with an example patch in the downloads section please? 
Seems like it'll take just a second and save quite a lot time for people like me

**Comment by arronsmith** [comment]
There's a test build in the builds folder at https://www.dropbox.com/sh/7sbvrhkfotsb1nu/AACiZo3n8-Mr1MPlXx1Cy2a8a?dl=0 - Tested on 34.2, 35.

The Hap plugin relies on an upstream change to FeralTic - vux has accepted a PR so I imagine this will make its way into a release of vvvv-dx11 at some point, but for now you'll need to replace your vvvv-dx11 pack with the one in the Dropbox link above. Usual caveats about backing up your vvvv directory, etc.

I'll probably upload something to contributions tomorrow for the wider vvvv community to have a  look at.

**Comment by leavittx** [comment]
I got a red node for HapAVITexture (vvvv-HapTreats.dll is missing), while the DX11 nodes work ok.
Tested on vvvv_50beta35_x64

**Comment by arronsmith** [comment]
hmmm, works for us. Possibly a Dropbox sync thing - please try extracting
haptreats_1_1.zip (in the builds folder) to your packs dir.

**Comment by leavittx** [comment]
No such file!

**Comment by arronsmith** [comment]
https://www.dropbox.com/s/m7iin63hwbqw899/haptreats_1_1.zip?dl=0

**Comment by leavittx** [comment]
Hey, I got it working! Your last response was super fast!

**Comment by leavittx** [comment]
I saw that you've solved the issue with AVI parsing, any chance to update the binaries up to that commit?

**Comment by arronsmith** [comment]
https://www.dropbox.com/s/rolt0buoe043h0j/haptreats_1_2.zip?dl=0

**Comment by leavittx** [comment]
Cool! It works!

**Comment by arronsmith** [comment]
Excellent - I have some suggestions by @Tebjan to implement over the weekend (inc. some performance enhancements) and then I'll probably try to shove a build into Contributions...

**Comment by tebjan** [comment]
this DX11 build works the HAP player. https://github.com/mrvux/dx11-vvvv/releases/tag/0.9.62-alpha
