### ISSUE TITLE
vvvv becomes non-responsive

### ISSUE THREAD

**Issue by leavittx** [artistsandengineers/AE_HapTools#2]
I was trying to load a small test file, but vvvv becomes non-responsive while loading it!
Here is the file: https://www.dropbox.com/s/c2fzmzykaudpra9/out_hap.avi?dl=0
I made the file out from mov using the following command: 
ffmpeg -i out_hap.mov  -vcodec copy out_hap.avi
Could you confirm such behavior in your case?

**Comment by leavittx** [comment]
Should I re-encode?

**Comment by arronsmith** [comment]
Will investigate now - just cloning the repo on my laptop...

**Comment by arronsmith** [comment]
Interesting - you seem to have uncovered a bug in my AVI parsing. It's not immediately clear what it is about your file that is different, but I'll figure it out in the morning and provide a fix.

Also we should throw an exception here, not hang vvvv indefinitely.

**Comment by leavittx** [comment]
Nice, keep me updated on this issue!
